server:
  port: 8080
spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      mvc:
        routes:
          - id: waste_manager
            uri: http://localhost:9090
            predicates:
              - Path=/waste-manager/**
          - id: waste_manager_address
            uri: http://localhost:8090
            predicates:
              - Path=/waste-manager-address/**
eureka:
  client:
    register-with-eureka: false
